export const SET_COMPANIES = "SET_COMPANIES";
export const COMPANIES_ERROR = "COMPANIES_ERROR";

export const UPDATE_COMPANY = "UPDATE_COMPANY";
export const UPDATE_COMPANY_LOADER = "UPDATE_COMPANY_LOADER";

export const ADD_USER = "ADD_USER";
